export const DATA = [
  {
    id: 1,
    title: 'Modern JS: A curated collection',
  },
  {
    id: 2,
    title: 'JavaScript notes for professionals',
  },
  {
    id: 3,
    title: 'JavaScript: The Good Parts',
  },
  {
    id: 4,
    title: 'JavaScript: The right way',
  },
  {
    id: 5,
    title: 'Exploring ES6',
  },
  {
    id: 6,
    title: 'JavaScript Enlightenment',
  },
  {
    id: 7,
    title: 'You dont know JS',
  },
  {
    id: 8,
    title: 'Learn JavaScript',
  },
  {
    id: 9,
    title: 'JavaScript succintly',
  },
  {
    id: 10,
    title: 'Human JavaScript',
  },
  {
    id: 11,
    title: 'JavaScript design patterns',
  },
  {
    id: 12,
    title: 'JS50: 50 illustrations in JS',
  },
  {
    id: 13,
    title: 'Eloqent JavaScript',
  },
  {
    id: 14,
    title: 'Practical ES6',
  },
  {
    id: 15,
    title: 'Speaking JavaScript',
  },
];

export const LIST = [
  {
    countryEN: 'Indonesia',
    country: 'IDN',
    siteCount: 3664,
    priMonthSitePoll: 10700.68,
    agent: 27,
    directCount: 1782,
    week: '1',
    priMonthSitePercent: 46.22,
    countryCH: '印尼',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 187.06,
    monthSitePoll: 7158.1,
    center: 81,
    monthDaySitePercent: 52.26,
    priMonthAgentPoll: 4945.52,
    monthSitePercent: 52.26,
    sitePercent: 51.36,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/IDN.png',
    monthAgentPoll: 3741.1,
    curSitePoll: 79.92,
    monthDaySitePoll: 357.91,
    agentCount: 1882,
    curAgentPoll: 45.61,
    curSitePercent: 57.08,
  },
  {
    countryEN: 'Philippines',
    country: 'PHL',
    siteCount: 1617,
    priMonthSitePoll: 3926.03,
    agent: 10,
    directCount: 764,
    week: '1',
    priMonthSitePercent: 59.64,
    countryCH: '菲律宾',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 82.49,
    monthSitePoll: 2665.95,
    center: 88,
    monthDaySitePercent: 61.89,
    priMonthAgentPoll: 2341.32,
    monthSitePercent: 61.89,
    sitePercent: 52.75,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/PHL.png',
    monthAgentPoll: 1649.85,
    curSitePoll: 58.32,
    monthDaySitePoll: 133.3,
    agentCount: 853,
    curAgentPoll: 32.28,
    curSitePercent: 55.35,
  },
  {
    countryEN: 'Vietnam',
    country: 'VNM',
    siteCount: 1962,
    priMonthSitePoll: 1816.83,
    agent: 18,
    directCount: 1665,
    week: '1',
    priMonthSitePercent: 13.75,
    countryCH: '越南',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 8.4,
    monthSitePoll: 1212.88,
    center: 61,
    monthDaySitePercent: 13.85,
    priMonthAgentPoll: 249.85,
    monthSitePercent: 13.85,
    sitePercent: 15.14,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/VNM.png',
    monthAgentPoll: 168.03,
    curSitePoll: 22.52,
    monthDaySitePoll: 60.64,
    agentCount: 297,
    curAgentPoll: 2.66,
    curSitePercent: 11.81,
  },
  {
    countryEN: 'Thailand',
    country: 'THA',
    siteCount: 2673,
    priMonthSitePoll: 3751.49,
    agent: 22,
    directCount: 1160,
    week: '1',
    priMonthSitePercent: 54.52,
    countryCH: '泰国',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 70.48,
    monthSitePoll: 2645.51,
    center: 21,
    monthDaySitePercent: 53.29,
    priMonthAgentPoll: 2045.39,
    monthSitePercent: 53.28,
    sitePercent: 56.6,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/THA.png',
    monthAgentPoll: 1409.66,
    curSitePoll: 60.61,
    monthDaySitePoll: 132.27,
    agentCount: 1513,
    curAgentPoll: 29.79,
    curSitePercent: 49.15,
  },
  {
    countryEN: 'Malaysia',
    country: 'MYS',
    siteCount: 1544,
    priMonthSitePoll: 1476.73,
    agent: 19,
    directCount: 248,
    week: '1',
    priMonthSitePercent: 81.33,
    countryCH: '马来',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 43.97,
    monthSitePoll: 1084.38,
    center: 12,
    monthDaySitePercent: 81.09,
    priMonthAgentPoll: 1200.95,
    monthSitePercent: 81.09,
    sitePercent: 83.94,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/MYS.png',
    monthAgentPoll: 879.34,
    curSitePoll: 17,
    monthDaySitePoll: 54.22,
    agentCount: 1296,
    curAgentPoll: 14.93,
    curSitePercent: 87.81,
  },
  {
    countryEN: 'Cambodia',
    country: 'KHM',
    siteCount: 742,
    priMonthSitePoll: 87.14,
    agent: 10,
    directCount: 92,
    week: '1',
    priMonthSitePercent: 26.61,
    countryCH: '柬埔寨',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 0.78,
    monthSitePoll: 58.19,
    center: 2,
    monthDaySitePercent: 26.95,
    priMonthAgentPoll: 23.19,
    monthSitePercent: 26.95,
    sitePercent: 87.6,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/KHM.png',
    monthAgentPoll: 15.68,
    curSitePoll: 0.9,
    monthDaySitePoll: 2.91,
    agentCount: 650,
    curAgentPoll: 0.33,
    curSitePercent: 36.43,
  },
  {
    countryEN: 'Singapore',
    country: 'SGP',
    siteCount: 515,
    priMonthSitePoll: 170.13,
    agent: 2,
    directCount: 515,
    week: '1',
    priMonthSitePercent: 0,
    countryCH: '新加坡',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 0,
    monthSitePoll: 112.9,
    center: 6,
    monthDaySitePercent: 0,
    priMonthAgentPoll: 0,
    monthSitePercent: 0,
    sitePercent: 0,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/SGP.png',
    monthAgentPoll: 0,
    curSitePoll: 2.38,
    monthDaySitePoll: 5.62,
    agentCount: 0,
    curAgentPoll: 0,
    curSitePercent: 0,
  },
  {
    countryEN: 'The United Arab Emirates',
    country: 'AE',
    siteCount: 18,
    priMonthSitePoll: 21.22,
    agent: 2,
    directCount: 18,
    week: '1',
    priMonthSitePercent: 0,
    countryCH: '阿联酋',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 0,
    monthSitePoll: 16.73,
    center: 7,
    monthDaySitePercent: 0,
    priMonthAgentPoll: 0,
    monthSitePercent: 0,
    sitePercent: 0,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/AED.png',
    monthAgentPoll: 0,
    curSitePoll: 0.002,
    monthDaySitePoll: 0.84,
    agentCount: 0,
    curAgentPoll: 0,
    curSitePercent: 0,
  },
  {
    countryEN: 'Kingdom of Saudi Arabia',
    country: 'KSA',
    siteCount: 60,
    priMonthSitePoll: 29.8,
    agent: 2,
    directCount: 60,
    week: '1',
    priMonthSitePercent: 0,
    countryCH: '沙特',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 0,
    monthSitePoll: 28.86,
    center: 18,
    monthDaySitePercent: 0,
    priMonthAgentPoll: 0,
    monthSitePercent: 0,
    sitePercent: 0,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/KSA.png',
    monthAgentPoll: 0,
    curSitePoll: 0.15,
    monthDaySitePoll: 1.44,
    agentCount: 0,
    curAgentPoll: 0,
    curSitePercent: 0,
  },
  {
    countryEN: 'Los Estados Unidos Mexicanos',
    country: 'MXP',
    siteCount: 183,
    priMonthSitePoll: 31.71,
    agent: 12,
    directCount: 183,
    week: '1',
    priMonthSitePercent: 0,
    countryCH: '墨西哥',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 0,
    monthSitePoll: 43.8,
    center: 22,
    monthDaySitePercent: 0,
    priMonthAgentPoll: 0,
    monthSitePercent: 0,
    sitePercent: 0,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/MXP.png',
    monthAgentPoll: 0,
    curSitePoll: 0.002,
    monthDaySitePoll: 2.19,
    agentCount: 0,
    curAgentPoll: 0,
    curSitePercent: 0,
  },
  {
    countryEN: 'Ancient Egypt',
    country: 'EGY',
    siteCount: 62,
    priMonthSitePoll: 15.45,
    agent: 13,
    directCount: 61,
    week: '1',
    priMonthSitePercent: 0.02,
    countryCH: '埃及',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 0.0001,
    monthSitePoll: 12.73,
    center: 3,
    monthDaySitePercent: 0.01,
    priMonthAgentPoll: 0.003,
    monthSitePercent: 0.01,
    sitePercent: 1.61,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/EGP.png',
    monthAgentPoll: 0.002,
    curSitePoll: 0.01,
    monthDaySitePoll: 0.64,
    agentCount: 1,
    curAgentPoll: 0,
    curSitePercent: 0,
  },
  {
    countryEN: 'The Federative Republic of Brazil',
    country: 'BRA',
    siteCount: 0,
    priMonthSitePoll: 0,
    agent: 0,
    directCount: 0,
    week: '1',
    priMonthSitePercent: 0,
    countryCH: '巴西',
    sendDate: '2022-08-21',
    monthDayAgentPoll: 0,
    monthSitePoll: 0,
    center: 0,
    monthDaySitePercent: 0,
    priMonthAgentPoll: 0,
    monthSitePercent: 0,
    sitePercent: 0,
    imgUrl: 'http://bi.jnt-express.net/yunlu-datacenter-web/image/BRL.png',
    monthAgentPoll: 0,
    curSitePoll: 0,
    monthDaySitePoll: 0,
    agentCount: 0,
    curAgentPoll: 0,
    curSitePercent: 0,
  },
];
